appName: adService
appImage: gcr.io/google-samples/microservices-demo/adService
appVersion: v.0.2.3
appReplicas: 2
containerPort: 9555
# list that we difined with range
containerEnvVars:
# change key , value to name and value to directly copy value from our config file
- name: PORT
  value: "8080"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"


servicePort: 5000
# we can delete this because the defaut service type is clusterIP
#serviceType: clusterIP
