appName: recommandationservice
appImage: gcr.io/google-samples/microservices-demo/recommandationservice
appVersion: v.0.2.3
appReplicas: 2
containerPort: 8080
# list that we difined with range
containerEnvVars:
# change key , value to name and value to directly copy value from our config file
- name: PORT
  value: "8080"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"
- name: DISABLE_DEBUGGER
  value: "1"



servicePort: 8080
# we can delete this because the defaut service type is clusterIP
#serviceType: clusterIP
