---
## services
- apiVersion: V1
- kind: Service
# specification MS
# this service email can be accesible with this name on this port 5000
- metadata:
  name: {{.Values.appName}} 
- spec:
  type: {{ .Values.serviceType}}
  - selector:
    app: {{.Values.appName}}
  - ports:
    - protocol: TCP
    ## service port can be the same or different from Container Port
      port: {{.Values.servicePort}}
## service port 
      targetPort: {{.Values.containerPort}}
