appName: shippingservice
appImage: gcr.io/google-samples/microservices-demo/shippingservice
appVersion: v.0.2.3
appReplicas: 2
containerPort: 50051
# list that we difined with range
containerEnvVars:
# change key , value to name and value to directly copy value from our config file
- name: PORT
  value: "50051"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"


servicePort: 50051
# we can delete this because the defaut service type is clusterIP
#serviceType: clusterIP
